# Generated by Django 4.1.4 on 2022-12-30 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app1", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Employees",
        ),
    ]
